//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace EMailAdmin.EMailSenderInformationTesting {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EMailSenderInformationServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EMailSenderInformationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetPaxPassedAwayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EMailSenderInformationService() {
            this.Url = global::EMailAdmin.Properties.Settings.Default.EMailAdmin_EMailSenderInformationTesting_EMailSenderInformationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetPaxPassedAwayCompletedEventHandler SetPaxPassedAwayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetPaxPassedAway", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetPaxPassedAway(int countryCode, string voucherCode, string nationalId, bool passedAway, string user, string password) {
            this.Invoke("SetPaxPassedAway", new object[] {
                        countryCode,
                        voucherCode,
                        nationalId,
                        passedAway,
                        user,
                        password});
        }
        
        /// <remarks/>
        public void SetPaxPassedAwayAsync(int countryCode, string voucherCode, string nationalId, bool passedAway, string user, string password) {
            this.SetPaxPassedAwayAsync(countryCode, voucherCode, nationalId, passedAway, user, password, null);
        }
        
        /// <remarks/>
        public void SetPaxPassedAwayAsync(int countryCode, string voucherCode, string nationalId, bool passedAway, string user, string password, object userState) {
            if ((this.SetPaxPassedAwayOperationCompleted == null)) {
                this.SetPaxPassedAwayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPaxPassedAwayOperationCompleted);
            }
            this.InvokeAsync("SetPaxPassedAway", new object[] {
                        countryCode,
                        voucherCode,
                        nationalId,
                        passedAway,
                        user,
                        password}, this.SetPaxPassedAwayOperationCompleted, userState);
        }
        
        private void OnSetPaxPassedAwayOperationCompleted(object arg) {
            if ((this.SetPaxPassedAwayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPaxPassedAwayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetPaxPassedAwayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591