-- =============================================
-- Author:	María de los Ángeles Fortelli
-- Create date: 12/08/2014
-- Description: Rimac Class Estrategy
-- =============================================
  IF NOT EXISTS ( SELECT IdEstrategy from EMailAdmin.dbo.Estrategy WHERE Code = 'BNFTRIMAC')
  INSERT INTO EMailAdmin.dbo.Estrategy
			([Code], 
			[Description], 
			[Class])
  VALUES
			('BNFTRIMAC', 
			'Main Benefits Rimac', 
			'EMailAdmin.BackEnd.Strategies.Attachment.MainBenefitsRimacAttachStrategy')
  
  DECLARE @IdStrategy int = (SELECT IdEstrategy FROM EMailAdmin.dbo.Estrategy WHERE Code = 'BNFTRIMAC')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ReportTitle'	,'Datos del Contratante / Asegurado')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'LastNameNameTitle'	,'Apellido y nombre')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardTitle',	'Tarjeta')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardValidFromTitle',	'Inicio de Vigencia')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardValidToTitle',	'Fin de vigencia')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardDaysTitle',	'Días')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardAreaTitle'	,'Zona de destino')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardEmissionDateTitle',	'Fecha de Emisión')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CardAmountTitle',	'Tarifa')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoTitle',	'Datos Personales')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoPassportTitle',	'Pasaporte Nro')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoAgeTitle', 'Edad')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoAddressTitle',	'Domicilio')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoCountryTitle',	'País')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PersonalInfoPhoneTitle',	'Teléfono')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EmergencyTitle',	'Datos de Emergencia')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EmergencyContactTitle',	'Nombre del contacto')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EmergencyPhoneTitle',	'Teléfono')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EmergencyAddressTitle',	'Domicilio')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ConditionsReportTitle',	'CONDICIONES PARTICULARES - LIMITES Y TOPES')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'SecureTypeTitle',	'Seguro de Viaje Individual')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ParticularConditionTitle',	'Condiciones Particulares')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CompanyPolizaDataTitle',	'Datos de la compañía aseguradora y de la póliza de seguro')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PolizaTitle',	'Póliza No')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'CompanyDataTitle',	'Compañía aseguradora: Rimac Internacional Compañía de Seguros y Reaseguros')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'RUCTitle',	'RUC')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyAdressTitle',	'Dirección')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyProvinceTitle',	'Provincia')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyPhoneTitle',	'Teléfono')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyDistrictTitle',	'Distrito')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyDepartamentTitle',	'Departamento')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AgencyFaxTitle',	'Fax')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaxTypeTitle',	'Tipo de Persona')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaxDocumentNumberTitle',	'Documento')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaxCityTitle',	'Ciudad')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaxBirthDateTitle',	'Fecha de Nacimiento')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaxEmailTitle',	'E-mail')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'DependentTitle',	'Asegurados dependientes (sólo para plan familiar)')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'DependentNameTitle',	'Nombres')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'DependentBirthDayTitle'	,'Fecha de Nacimiento')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'BeneficiariesTitle',	'Beneficiarios')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'InsuredTitle',	'Coberturas y sumas aseguradas')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'Dependent',	'Los Asegurados dependientes no gozarán de las coberturas de Muerte Accidental ni de Invalidez Total y Permanente. En virtud de ello, es que, para el presente producto, no es aplicable el tercer párrafo del literal a) del numeral 1 y tampoco el segundo párrafo del literal b) del numeral 1 del condicionado general (cobertura adicional de muerte accidental e invalidez total y permanente por accidente).')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'Beneficiaries'	,'El beneficiario de las coberturas descritas en el Condicionado General, es el ASEGURADO. Sin embargo, en el caso de la cobertura de Muerte Accidental los beneficiarios serán los Herederos Legales.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ConsiderationsTitle',	'CONSIDERACIONES:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'Considerations'	,'De acuerdo a lo señalado en el literal a) del Artículo 8 de las Condiciones Generales, las enfermedades preexistentes conocidas o no por el Asegurado Titular, están excluídas de este seguro.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaymentPlanTitle'	,'Plan de Pago')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PrimaNetaTitle'	,'PRIMA NETA:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'AllowanceTitle',	'DERECHO DE EMISIÓN:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'IGVTitle'	,'IGV:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PrimaTotalTitle',	'PRIMA TOTAL:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PaymentPlanNote',	'Las cuotas consideran los impuestos vigentes al momento de su emisión.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'FeaturesOfProductTitle',	'Características de Producto')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'MinAge',	'Edad mínima de ingreso a la póliza: 18 años.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'MaxAge'	,'Edad Máxima de ingreso y permanencia al seguro: 75 años.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'Others'	,'Deducibles / Franquicias / Coaseguros / Similares (A Cargo del Asegurado): No Aplica.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureTitle'	,'Procedimiento en caso de siniestros')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EspecialConditionsTitle',	'Condiciones Especiales')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'EspecialConditions',	'- En caso de anulación de la póliza por negación de visa, se deberá adjuntar los documentos que demuestren dicha negación. La Compañía cobrará US$ 15 por concepto de gastos administrativos y de anulación, monto que será deducido de la prima que la COMPAÑÍA devolverá al Asegurado Titular. -Mínimo de días de viaje: 3 días calendarios.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ImportantTitle',	'Importante')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'Important',	'La aceptación de la solicitud del seguro supone la conformidad de las  declaraciones efectuadas en ella por el Contratante o Asegurado en los términos estipulados por las empresas, en tanto el Contratante o Asegurado hubieran proporcionado información veraz. El CONTRATANTE/ASEGURADO  firma la presente Póliza en señal de haber tomado conocimiento, recibido y aceptado las Condiciones Generales, Condiciones Particulares, Cláusulas Adicionales y el resumen de la Póliza.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'PrintDateTitle',	'Fecha:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureOne',	'El ASEGURADO deberá contactar con la Central de Asistencia de la COMPAÑÍA al número (511)213-6641 o a los siguientes números en el extranjero: Argentina 54-11-598-42134 Brasil 55-11-395-70393 Canadá 1-438-800-2769 Chile 56-2-938-1617 España 34-0911-815?928/34-901-667-850* Italia 39-06-993- 37150 Sudáfrica 27-10-500-8789 Suiza 41-43-508-1824 Reino Unido 44-84-337-80120 Japón 81-3-457-90583 USA 1-305?705-6937/1-888-892-5195* México 52-55-462-82537 Colombia 57-1-589-7680 Venezuela 58-212-335-7611.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureTwo',	'Para otros países llamadas por cobrar a Perú 51-1-707-1371. * Números sin cargo (Solo para llamadas dentro de esos países).')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureThree',	'Cuando se trate de un problema de salud, cuya emergencia imposibilite la comunicación previa a la Central de Asistencia, el ASEGURADO se encuentra obligado a comunicar el evento dentro de las 24 horas siguientes al inicio de la emergencia, informando las razones que le impidieron dar el aviso en forma oportuna:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureFour',	'En esta llamada el ASEGURADO deberá informar:')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureFive',	'a) Su nombre y el número de la póliza;')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureSix',	'b) El lugar y el teléfono donde se encuentra;')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureSeven',	'c) El problema y el tipo de información o ayuda necesarias.')
  INSERT INTO EMailAdmin.dbo.ReportLanguage (IdLanguage, IdStrategy, [Key], Value) VALUES (1, @IdStrategy,	'ProcedureEigth',	'Para cualquier consulta o reclamo sobre el presente seguro, o ante la ocurrencia de un siniestro, el Asegurado podrá comunicarse al 213-6641.')