USE [EMailAdmin]
GO

/****** Object:  Index [IDX_CODE]    Script Date: 03/21/2013 11:45:58 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_CODE] ON [dbo].[EMailListType] 
(
	[Code] ASC,
	[IdStatus] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

